### ISSUE TITLE
reduced output from references_read()

### ISSUE THREAD

**Issue by embruna** [embruna/refnet#49]
I think we can greatly reduce the number of columns provided in the csv and R object by references_read() - the following all have NAs for all rows and are not really relevant for the vast majority of analyses.  

*CC
*CH
*CL Conference Location
*CT Conference Title
*CY Conference Date
*DT Document Type
*FX Funding Text
*GA Group Authors
*GE
*ID Keywords Plus?
*IS
*J9 29-Character Source Abbreviation
*JI ISO Source Abbreviation
*LA
*LT
*MC
*MI
*NR
*PA Publisher Address
*PI Publisher City
*PN Part Number
*PS
*RID (discontinued field tag for ResearcherID Number
*SI Special Issue
*SU Supplement
*TA
*VR Version Number

Is there way to have these dumped into the csv/Robject ONLY if the user wants them, e.g.,  the trimmed output is default and `all.fields=T` (or whatever the right syntax is) below: 

`Brazil_references <- references_read(data = './data/Brazil.txt', dir = F, all.fields=T, filename_root = './output/Brazil')`

**Comment by aurielfournier** [comment]
Done!
